from __future__ import annotations

import os
import re
import subprocess
from pathlib import Path

import pytest

pytestmark = pytest.mark.unit

PROJECT_ROOT = Path(__file__).resolve().parents[1]
MAKEFILE_PATH = PROJECT_ROOT / "requirements" / "Makefile"


def _read_makefile() -> str:
    return MAKEFILE_PATH.read_text(encoding="utf-8")


def _target_body(name: str) -> str:
    text = _read_makefile()
    match = re.search(rf"^{re.escape(name)}:(?:[^\n]*)\n(?P<body>(?:\t.*\n)+)", text, flags=re.MULTILINE)
    assert match is not None, f"Makefile target {name} not found"
    return match.group("body")


def test_generic_targets_do_not_reference_target_owned_ml_locks() -> None:
    text = _read_makefile()
    assert "compile: compile-generic" in text
    assert "update: update-generic" in text
    assert "check: check-generic" in text

    for target in ("compile-generic", "update-generic", "check-generic"):
        body = _target_body(target)
        assert "ml-core-darwin-arm64.txt" not in body
        assert "ml-core-darwin-x86_64.txt" not in body
        assert "ml-core-linux.txt" not in body


def test_check_generic_normalizes_host_specific_generic_lock_packages() -> None:
    body = _target_body("check-generic")

    for snippet in (
        "all.txt:jeepney==*",
        "all.txt:secretstorage==*",
        "all.txt:opencv-python==*",
        "all.txt:opencv-python-headless==*",
        "base.txt:opencv-python==*",
        "base.txt:opencv-python-headless==*",
        "ci.txt:cffi==*",
        "ci.txt:cryptography==*",
        "ci.txt:jeepney==*",
        "ci.txt:pycparser==*",
        "ci.txt:secretstorage==*",
    ):
        assert snippet in body


def _write_fake_pip_compile(path: Path, *, version: str = "7.6.1") -> None:
    path.write_text(
        """#!/usr/bin/env python3
from pathlib import Path
import sys

if "--version" in sys.argv:
    print("pip-compile, version __PIP_TOOLS_VERSION__")
    raise SystemExit(0)

if "--help" in sys.argv:
    print("fake pip-compile")
    raise SystemExit(0)

output = None
for index, arg in enumerate(sys.argv):
    if arg == "-o":
        output = sys.argv[index + 1]
        break
    if arg.startswith("--output-file="):
        output = arg.split("=", 1)[1]
        break

if output is None:
    raise SystemExit("missing output path")

path = Path(output)
header = [
    "#",
    "# This file is autogenerated by pip-compile with Python 3.11",
    "# by the following command:",
    "#",
    f"#    fake pip-compile --output-file={path.name}",
]

if path.name in {"all.txt", "base.txt"}:
    body = [
        "numpy==9.9.9",
        "opencv-python-headless==4.14.0.92",
        "    # via -r base.in",
        "packaging==99.0",
    ]
else:
    body = ["packaging==99.0"]

path.write_text("\\n".join(header + body) + "\\n", encoding="utf-8")
""".replace("__PIP_TOOLS_VERSION__", version),
        encoding="utf-8",
    )
    path.chmod(0o755)


def _write_fake_pip_python(path: Path, *, version: str = "26.2.1") -> None:
    path.write_text(
        "#!/bin/sh\n"
        'if [ "$1" = "-m" ] && [ "$2" = "pip" ] && [ "$3" = "--version" ]; then\n'
        f'  echo "pip {version} from /test/site-packages/pip (python 3.11)"\n'
        "  exit 0\n"
        "fi\n"
        "exit 2\n",
        encoding="utf-8",
    )
    path.chmod(0o755)


@pytest.mark.security
def test_require_pip_compile_rejects_stale_toolchain(tmp_path: Path) -> None:
    fake_pip_compile = tmp_path / "pip-compile"
    fake_pip_python = tmp_path / "python"
    _write_fake_pip_compile(fake_pip_compile, version="7.5.2")
    _write_fake_pip_python(fake_pip_python)

    result = subprocess.run(
        [
            "make",
            "require-pip-compile",
            f"PIP_COMPILE_BIN={fake_pip_compile}",
            f"PIP_PYTHON_BIN={fake_pip_python}",
        ],
        cwd=MAKEFILE_PATH.parent,
        env=os.environ.copy(),
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode != 0
    output = result.stdout + result.stderr
    assert "requires pip-tools==7.6.1" in output
    assert "pip-compile, version 7.5.2" in output


@pytest.mark.security
def test_require_pip_compile_rejects_stale_pip_runtime(tmp_path: Path) -> None:
    fake_pip_compile = tmp_path / "pip-compile"
    fake_pip_python = tmp_path / "python"
    _write_fake_pip_compile(fake_pip_compile)
    _write_fake_pip_python(fake_pip_python, version="26.1.2")

    result = subprocess.run(
        [
            "make",
            "require-pip-compile",
            f"PIP_COMPILE_BIN={fake_pip_compile}",
            f"PIP_PYTHON_BIN={fake_pip_python}",
        ],
        cwd=MAKEFILE_PATH.parent,
        env=os.environ.copy(),
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode != 0
    output = result.stdout + result.stderr
    assert "requires pip==26.2.1" in output
    assert "pip 26.1.2 from /test/site-packages/pip" in output


@pytest.mark.security
def test_require_pip_compile_accepts_exact_governed_toolchain(tmp_path: Path) -> None:
    fake_pip_compile = tmp_path / "pip-compile"
    fake_pip_python = tmp_path / "python"
    _write_fake_pip_compile(fake_pip_compile)
    _write_fake_pip_python(fake_pip_python)

    result = subprocess.run(
        [
            "make",
            "require-pip-compile",
            f"PIP_COMPILE_BIN={fake_pip_compile}",
            f"PIP_PYTHON_BIN={fake_pip_python}",
        ],
        cwd=MAKEFILE_PATH.parent,
        env=os.environ.copy(),
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode == 0, result.stdout + result.stderr


def _write_lock_with_opencv_marker_pins(path: Path) -> None:
    path.write_text(
        "\n".join(
            [
                "#",
                "# This file is autogenerated by pip-compile with Python 3.11",
                "# by the following command:",
                "#",
                f"#    pip-compile --output-file={path.name}",
                "numpy==2.4.4",
                'opencv-python==4.13.0.92 ; platform_system != "Linux"',
                "    # via -r base.in",
                'opencv-python-headless==4.13.0.92 ; platform_system == "Linux"',
                "    # via -r base.in",
                "packaging==26.0",
            ]
        )
        + "\n",
        encoding="utf-8",
    )


def test_update_generic_preserves_governed_opencv_marker_pins_and_fresh_versions(tmp_path: Path) -> None:
    repo_root = tmp_path / "repo"
    requirements_dir = repo_root / "requirements"
    utilities_dir = repo_root / "scripts" / "utilities"
    requirements_dir.mkdir(parents=True)
    utilities_dir.mkdir(parents=True)
    (requirements_dir / "Makefile").write_text(MAKEFILE_PATH.read_text(encoding="utf-8"), encoding="utf-8")
    (utilities_dir / "restore_requirement_marker_pins.py").write_text(
        (PROJECT_ROOT / "scripts" / "utilities" / "restore_requirement_marker_pins.py").read_text(encoding="utf-8"),
        encoding="utf-8",
    )

    for name in ("all.in", "base.in", "dev.in", "ci.in", "security.in", "tools-archive.in"):
        (requirements_dir / name).write_text("# test input\n", encoding="utf-8")
    for name in ("all.txt", "base.txt"):
        _write_lock_with_opencv_marker_pins(requirements_dir / name)

    fake_pip_compile = tmp_path / "pip-compile"
    fake_pip_python = tmp_path / "python"
    _write_fake_pip_compile(fake_pip_compile)
    _write_fake_pip_python(fake_pip_python)

    result = subprocess.run(
        [
            "make",
            "update-generic",
            f"PIP_COMPILE_BIN={fake_pip_compile}",
            f"PIP_PYTHON_BIN={fake_pip_python}",
        ],
        cwd=requirements_dir,
        env=os.environ.copy(),
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode == 0, result.stdout + result.stderr
    for name in ("all.txt", "base.txt"):
        text = (requirements_dir / name).read_text(encoding="utf-8")
        assert 'opencv-python==4.14.0.92 ; platform_system != "Linux"' in text
        assert 'opencv-python-headless==4.14.0.92 ; platform_system == "Linux"' in text
        assert "opencv-python==4.13.0.92" not in text
        assert "opencv-python-headless==4.13.0.92" not in text


def test_compile_ml_layers_refuses_broad_target_owned_regeneration() -> None:
    body = _target_body("compile-ml-layers")

    assert "target-owned ML locks require explicit authoritative-lane commands" in body
    assert "compile-ml-darwin-arm64" in body
    assert "compile-ml-linux-x86_64" not in body


def _write_fake_uname(fakebin: Path, *, system: str, machine: str) -> None:
    (fakebin / "uname").write_text(
        "#!/bin/sh\n"
        'case "$1" in\n'
        f"  -s) echo {system} ;;\n"
        f"  -m) echo {machine} ;;\n"
        "  *) echo unsupported >&2; exit 1 ;;\n"
        "esac\n",
        encoding="utf-8",
    )
    (fakebin / "uname").chmod(0o755)


def test_darwin_arm64_target_fails_closed_off_lane(tmp_path: Path) -> None:
    repo_root = tmp_path / "repo"
    requirements_dir = repo_root / "requirements"
    requirements_dir.mkdir(parents=True)
    (requirements_dir / "Makefile").write_text(MAKEFILE_PATH.read_text(encoding="utf-8"), encoding="utf-8")
    fakebin = tmp_path / "fakebin"
    fakebin.mkdir()
    _write_fake_uname(fakebin, system="Linux", machine="x86_64")

    env = {**os.environ, "PATH": f"{fakebin}:/usr/bin:/bin"}
    result = subprocess.run(
        ["make", "compile-ml-darwin-arm64"],
        cwd=requirements_dir,
        env=env,
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode != 0
    assert "authoritative only on native Darwin arm64" in (result.stdout + result.stderr)


def test_retired_linux_x86_64_target_exits_nonzero_with_retired_message(tmp_path: Path) -> None:
    repo_root = tmp_path / "repo"
    requirements_dir = repo_root / "requirements"
    requirements_dir.mkdir(parents=True)
    (requirements_dir / "Makefile").write_text(MAKEFILE_PATH.read_text(encoding="utf-8"), encoding="utf-8")

    env = {**os.environ, "PATH": "/usr/bin:/bin"}
    result = subprocess.run(
        ["make", "compile-ml-linux-x86_64"],
        cwd=requirements_dir,
        env=env,
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode != 0
    assert "Linux ML lockfiles are retired unsupported manifests" in (result.stdout + result.stderr)


def test_retired_darwin_x86_64_target_exits_nonzero_with_retired_message(tmp_path: Path) -> None:
    repo_root = tmp_path / "repo"
    requirements_dir = repo_root / "requirements"
    requirements_dir.mkdir(parents=True)
    (requirements_dir / "Makefile").write_text(MAKEFILE_PATH.read_text(encoding="utf-8"), encoding="utf-8")

    env = {**os.environ, "PATH": "/usr/bin:/bin"}
    result = subprocess.run(
        ["make", "compile-ml-darwin-x86_64"],
        cwd=requirements_dir,
        env=env,
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode != 0
    assert "macOS Intel ML lockfiles are retired unsupported manifests" in (result.stdout + result.stderr)
