import importlib.util
from pathlib import Path

import pytest

pytestmark = pytest.mark.unit

PROJECT_ROOT = Path(__file__).resolve().parents[1]
TOOL_PATH = PROJECT_ROOT / "scripts" / "validation" / "check_requirements_lock_contract.py"
SPEC = importlib.util.spec_from_file_location("check_requirements_lock_contract", TOOL_PATH)
assert SPEC is not None and SPEC.loader is not None
contract = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(contract)


def write_makefile(tmp_path: Path, version: str = "3.11") -> None:
    (tmp_path / "requirements").mkdir()
    (tmp_path / "requirements" / "Makefile").write_text(
        f"LOCK_PYTHON_VERSION ?= {version}\n",
        encoding="utf-8",
    )


def write_lockfile(tmp_path: Path, name: str, python_version: str, body: str = "") -> None:
    (tmp_path / "requirements" / name).write_text(
        "\n".join(
            [
                "#",
                f"# This file is autogenerated by pip-compile with Python {python_version}",
                "# by the following command:",
                "#",
                "#    pip-compile ...",
                body,
            ]
        ).rstrip()
        + "\n",
        encoding="utf-8",
    )


def write_input_file(tmp_path: Path, name: str, body: str) -> None:
    (tmp_path / "requirements" / name).write_text(body.rstrip() + "\n", encoding="utf-8")


def write_lock_ownership_manifest(tmp_path: Path) -> None:
    (tmp_path / "requirements" / "lock_ownership.yml").write_text(
        "\n".join(
            [
                "version: 1",
                "locks:",
                "  all.txt:",
                "    target_id: generic",
                '    python_version: "3.11"',
                "    status: active",
                "    allowed_contexts:",
                "      - ubuntu-x64-generic",
                "  base.txt:",
                "    target_id: generic",
                '    python_version: "3.11"',
                "    status: active",
                "    allowed_contexts:",
                "      - ubuntu-x64-generic",
                "  dev.txt:",
                "    target_id: generic",
                '    python_version: "3.11"',
                "    status: active",
                "    allowed_contexts:",
                "      - ubuntu-x64-generic",
                "  ci.txt:",
                "    target_id: generic",
                '    python_version: "3.11"',
                "    status: active",
                "    allowed_contexts:",
                "      - ubuntu-x64-generic",
                "  security.txt:",
                "    target_id: generic",
                '    python_version: "3.11"',
                "    status: active",
                "    allowed_contexts:",
                "      - ubuntu-x64-generic",
                "  tools-archive.txt:",
                "    target_id: generic",
                '    python_version: "3.11"',
                "    status: active",
                "    allowed_contexts:",
                "      - ubuntu-x64-generic",
                "  ml-core-darwin-arm64.txt:",
                "    target_id: darwin-arm64",
                '    python_version: "3.11"',
                "    status: active",
                "    allowed_contexts:",
                "      - local-darwin-arm64",
            ]
        )
        + "\n",
        encoding="utf-8",
    )


@pytest.fixture(name="isolated_repo")
def fixture_isolated_repo(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    monkeypatch.setattr(contract, "REPO_ROOT", tmp_path)
    monkeypatch.setattr(contract, "REQUIREMENTS_DIR", tmp_path / "requirements")
    monkeypatch.setattr(contract, "MAKEFILE_PATH", tmp_path / "requirements" / "Makefile")
    monkeypatch.setattr(contract, "LOCK_OWNERSHIP_PATH", tmp_path / "requirements" / "lock_ownership.yml")
    write_makefile(tmp_path)
    write_lock_ownership_manifest(tmp_path)
    for name in contract.ALL_LOCK_FILES:
        write_lockfile(tmp_path, name, "3.11")
    write_lockfile(
        tmp_path,
        "ml-core-darwin-arm64.txt",
        "3.11",
        body="torch==2.8.0\ntorchvision==0.23.0\ndiffusers==0.38.0\ntransformers==5.0.0\ncoremltools==9.0\n",
    )
    return tmp_path


def test_headers_match_expected_python(isolated_repo: Path) -> None:
    expected = contract.read_expected_lock_python_version()
    assert contract.validate_lockfile_headers(expected) == []


def test_header_mismatch_is_reported(isolated_repo: Path) -> None:
    write_lockfile(isolated_repo, "base.txt", "3.12")
    expected = contract.read_expected_lock_python_version()
    errors = contract.validate_lockfile_headers(expected)
    assert errors == [f"{isolated_repo / 'requirements' / 'base.txt'} was generated with Python 3.12; " "expected Python 3.11"]


def test_missing_platform_core_lockfile_is_reported(isolated_repo: Path) -> None:
    (isolated_repo / "requirements" / "ml-core-darwin-arm64.txt").unlink()
    expected = contract.read_expected_lock_python_version()
    errors = contract.validate_lockfile_headers(expected)
    assert errors == [f"Missing required lockfile: {isolated_repo / 'requirements' / 'ml-core-darwin-arm64.txt'}"]


def test_missing_lock_ownership_manifest_entry_is_reported(isolated_repo: Path) -> None:
    manifest_path = isolated_repo / "requirements" / "lock_ownership.yml"
    manifest_path.write_text(
        manifest_path.read_text(encoding="utf-8").replace(
            '  base.txt:\n    target_id: generic\n    python_version: "3.11"\n    status: active\n    allowed_contexts:\n      - ubuntu-x64-generic\n',
            "",
            1,
        ),
        encoding="utf-8",
    )

    errors = contract.validate_lock_ownership_manifest()

    assert errors == ["requirements/lock_ownership.yml must declare governed lock 'base.txt'"]


def test_unexpected_lock_ownership_manifest_entry_is_reported(isolated_repo: Path) -> None:
    manifest_path = isolated_repo / "requirements" / "lock_ownership.yml"
    manifest_path.write_text(
        manifest_path.read_text(encoding="utf-8")
        + '\n  unexpected.txt:\n    target_id: unexpected\n    python_version: "3.11"\n    status: active\n    allowed_contexts:\n      - ubuntu-x64-generic\n',
        encoding="utf-8",
    )

    errors = contract.validate_lock_ownership_manifest()

    assert errors == ["requirements/lock_ownership.yml declares unexpected lock 'unexpected.txt'"]


def test_noncore_optional_lockfile_is_reported(isolated_repo: Path) -> None:
    write_lockfile(isolated_repo, "ml.txt", "3.11")
    errors = contract.validate_noncore_optional_lockfiles_absent()
    assert errors == [
        f"{isolated_repo / 'requirements' / 'ml.txt'} is not part of the checked-in "
        "lockfile contract; remove host-generated non-core ML layer artifacts from the repository"
    ]


def test_generic_lock_requires_linux_keyring_transitives_in_all_lock(isolated_repo: Path) -> None:
    write_lockfile(
        isolated_repo,
        "all.txt",
        "3.11",
        body="keyring==25.7.0\ncryptography==46.0.7\ncffi==2.0.0\npycparser==3.0\n",
    )

    errors = contract.validate_generic_linux_keyring_pins()

    assert errors == [
        f"{isolated_repo / 'requirements' / 'all.txt'} pins keyring==25.7.0 but is missing Linux keyring-chain packages "
        "'jeepney', 'secretstorage'. Regenerate the generic lock on ubuntu-x64-generic or restore the pinned "
        "Linux transitive dependencies explicitly."
    ]


def test_generic_lock_requires_linux_keyring_transitives_in_ci_lock(isolated_repo: Path) -> None:
    write_lockfile(
        isolated_repo,
        "ci.txt",
        "3.11",
        body="keyring==25.7.0\njeepney==0.9.0\nsecretstorage==3.5.0\n",
    )

    errors = contract.validate_generic_linux_keyring_pins()

    assert errors == [
        f"{isolated_repo / 'requirements' / 'ci.txt'} pins keyring==25.7.0 but is missing Linux keyring-chain packages "
        "'cffi', 'cryptography', 'pycparser'. Regenerate the generic lock on ubuntu-x64-generic or restore the pinned "
        "Linux transitive dependencies explicitly."
    ]


def test_generic_lock_accepts_complete_linux_keyring_chain(isolated_repo: Path) -> None:
    write_lockfile(
        isolated_repo,
        "all.txt",
        "3.11",
        body="keyring==25.7.0\njeepney==0.9.0\nsecretstorage==3.5.0\ncryptography==46.0.7\ncffi==2.0.0\npycparser==3.0\n",
    )
    write_lockfile(
        isolated_repo,
        "ci.txt",
        "3.11",
        body="keyring==25.7.0\njeepney==0.9.0\nsecretstorage==3.5.0\ncryptography==46.0.7\ncffi==2.0.0\npycparser==3.0\n",
    )

    errors = contract.validate_generic_linux_keyring_pins()

    assert errors == []


def test_generic_runtime_marker_pins_require_non_linux_opencv_in_base_lock(isolated_repo: Path) -> None:
    write_input_file(
        isolated_repo,
        "base.in",
        'opencv-python>=4.8.0,<5 ; platform_system != "Linux"\n'
        'opencv-python-headless>=4.8.0,<5 ; platform_system == "Linux"\n',
    )
    write_lockfile(
        isolated_repo,
        "all.txt",
        "3.11",
        body='opencv-python==4.13.0.92 ; platform_system != "Linux"\n'
        'opencv-python-headless==4.13.0.92 ; platform_system == "Linux"\n',
    )
    write_lockfile(
        isolated_repo,
        "base.txt",
        "3.11",
        body='opencv-python-headless==4.13.0.92 ; platform_system == "Linux"\n',
    )

    errors = contract.validate_generic_base_runtime_platform_marker_pins()

    assert errors == [
        f"{isolated_repo / 'requirements' / 'base.txt'} must retain 'opencv-python' because "
        f"{isolated_repo / 'requirements' / 'base.in'} declares it with marker 'platform_system != \"Linux\"'. "
        "Regenerate the generic lock on ubuntu-x64-generic or restore the pinned platform-marked runtime dependency."
    ]


def test_generic_runtime_marker_pins_require_non_linux_opencv_in_all_lock(isolated_repo: Path) -> None:
    write_input_file(
        isolated_repo,
        "base.in",
        'opencv-python>=4.8.0,<5 ; platform_system != "Linux"\n'
        'opencv-python-headless>=4.8.0,<5 ; platform_system == "Linux"\n',
    )
    write_lockfile(
        isolated_repo,
        "all.txt",
        "3.11",
        body='opencv-python-headless==4.13.0.92 ; platform_system == "Linux"\n',
    )
    write_lockfile(
        isolated_repo,
        "base.txt",
        "3.11",
        body='opencv-python==4.13.0.92 ; platform_system != "Linux"\n'
        'opencv-python-headless==4.13.0.92 ; platform_system == "Linux"\n',
    )

    errors = contract.validate_generic_base_runtime_platform_marker_pins()

    assert errors == [
        f"{isolated_repo / 'requirements' / 'all.txt'} must retain 'opencv-python' because "
        f"{isolated_repo / 'requirements' / 'base.in'} declares it with marker 'platform_system != \"Linux\"'. "
        "Regenerate the generic lock on ubuntu-x64-generic or restore the pinned platform-marked runtime dependency."
    ]


def test_generic_runtime_marker_pins_accept_expected_opencv_marker_packages(isolated_repo: Path) -> None:
    write_input_file(
        isolated_repo,
        "base.in",
        'opencv-python>=4.8.0,<5 ; platform_system != "Linux"\n'
        'opencv-python-headless>=4.8.0,<5 ; platform_system == "Linux"\n',
    )
    lock_body = (
        'opencv-python==4.13.0.92 ; platform_system != "Linux"\n'
        'opencv-python-headless==4.13.0.92 ; platform_system == "Linux"\n'
    )
    write_lockfile(isolated_repo, "all.txt", "3.11", body=lock_body)
    write_lockfile(isolated_repo, "base.txt", "3.11", body=lock_body)

    errors = contract.validate_generic_base_runtime_platform_marker_pins()

    assert errors == []


def test_platform_lock_wrong_os_marker_is_reported(isolated_repo: Path) -> None:
    write_lockfile(
        isolated_repo,
        "ml-core-darwin-arm64.txt",
        "3.11",
        body='torch==2.8.0\ncoremltools==9.0\ntorchvision==0.23.0\ntransformers==5.0.0 ; platform_system == "Linux"\n',
    )
    errors = contract.validate_platform_lock_markers()
    pattern = contract.PLATFORM_LOCK_FORBIDDEN_PATTERNS["ml-core-darwin-arm64.txt"][0]
    assert errors == [
        f"{isolated_repo / 'requirements' / 'ml-core-darwin-arm64.txt'}:9 contains forbidden platform marker pattern "
        f"{pattern!r} for this target lockfile"
    ]


def test_retired_linux_lockfile_is_reported(isolated_repo: Path) -> None:
    (isolated_repo / "requirements" / "ml-core-linux.txt").write_text(
        "torch==2.2.2\n",
        encoding="utf-8",
    )

    errors = contract.validate_retired_unsupported_ml_requirement_files_absent()

    assert errors == [
        f"{isolated_repo / 'requirements' / 'ml-core-linux.txt'} is a retired unsupported ML manifest; keep historical "
        "Linux/macOS Intel lane details in docs, not in scan-visible requirements files"
    ]


def test_retired_darwin_x86_input_is_reported(isolated_repo: Path) -> None:
    (isolated_repo / "requirements" / "ml-core-darwin-x86_64.in").write_text(
        "torch==2.2.2\n",
        encoding="utf-8",
    )

    errors = contract.validate_retired_unsupported_ml_requirement_files_absent()

    assert errors == [
        f"{isolated_repo / 'requirements' / 'ml-core-darwin-x86_64.in'} is a retired unsupported ML manifest; keep historical "
        "Linux/macOS Intel lane details in docs, not in scan-visible requirements files"
    ]


def test_darwin_arm64_input_requires_coremltools(isolated_repo: Path) -> None:
    (isolated_repo / "requirements" / "ml-core-darwin-arm64.in").write_text(
        "torch==2.8.0\ntorchvision==0.23.0\ndiffusers>=0.38.0,<1\ntransformers>=5.0.0,<5.1\n",
        encoding="utf-8",
    )

    errors = contract.validate_darwin_input_guards()

    assert errors == [
        f"{isolated_repo / 'requirements' / 'ml-core-darwin-arm64.in'} must declare coremltools so Apple Silicon CoreML support "
        "is part of the arm64 ML baseline contract."
    ]


def test_darwin_arm64_input_requires_supported_torch_pin(isolated_repo: Path) -> None:
    (isolated_repo / "requirements" / "ml-core-darwin-arm64.in").write_text(
        "torch==2.7.0\ntorchvision==0.23.0\ndiffusers>=0.38.0,<1\ntransformers>=5.0.0,<5.1\ncoremltools>=7.0\n",
        encoding="utf-8",
    )

    errors = contract.validate_darwin_input_guards()

    assert errors == [
        f"{isolated_repo / 'requirements' / 'ml-core-darwin-arm64.in'} must pin torch==2.8.0 for the supported Apple Silicon security baseline."
    ]


def test_darwin_arm64_input_requires_supported_torchvision_pin(isolated_repo: Path) -> None:
    (isolated_repo / "requirements" / "ml-core-darwin-arm64.in").write_text(
        "torch==2.8.0\ntorchvision==0.22.0\ndiffusers>=0.38.0,<1\ntransformers>=5.0.0,<5.1\ncoremltools>=7.0\n",
        encoding="utf-8",
    )

    errors = contract.validate_darwin_input_guards()

    assert errors == [
        f"{isolated_repo / 'requirements' / 'ml-core-darwin-arm64.in'} must pin torchvision==0.23.0 alongside the supported Apple Silicon torch baseline."
    ]


def test_darwin_arm64_input_requires_supported_transformers_range(isolated_repo: Path) -> None:
    (isolated_repo / "requirements" / "ml-core-darwin-arm64.in").write_text(
        "torch==2.8.0\ntorchvision==0.23.0\ndiffusers>=0.38.0,<1\ntransformers>=4.57.0,<5\ncoremltools>=7.0\n",
        encoding="utf-8",
    )

    errors = contract.validate_darwin_input_guards()

    assert errors == [
        f"{isolated_repo / 'requirements' / 'ml-core-darwin-arm64.in'} must declare 'transformers>=5.0.0,<5.1' "
        "for the supported Transformers security baseline."
    ]


def test_darwin_arm64_input_requires_supported_diffusers_range(isolated_repo: Path) -> None:
    (isolated_repo / "requirements" / "ml-core-darwin-arm64.in").write_text(
        "torch==2.8.0\ntorchvision==0.23.0\ndiffusers>=0.36.0,<1\ntransformers>=5.0.0,<5.1\ncoremltools>=7.0\n",
        encoding="utf-8",
    )

    errors = contract.validate_darwin_input_guards()

    assert errors == [
        f"{isolated_repo / 'requirements' / 'ml-core-darwin-arm64.in'} must declare 'diffusers>=0.38.0,<1' "
        "for the supported Diffusers security baseline."
    ]


def test_platform_lock_runtime_compatibility_requires_arm64_coremltools(isolated_repo: Path) -> None:
    write_lockfile(
        isolated_repo,
        "ml-core-darwin-arm64.txt",
        "3.11",
        body="torch==2.8.0\ntorchvision==0.23.0\ndiffusers==0.38.0\ntransformers==5.0.0\nnumpy==2.4.3\n",
    )

    errors = contract.validate_platform_lock_runtime_compatibility()

    assert errors == [
        f"{isolated_repo / 'requirements' / 'ml-core-darwin-arm64.txt'} must include a pinned coremltools dependency so Apple Silicon "
        "CoreML support remains part of the checked-in arm64 contract."
    ]


def test_platform_lock_runtime_compatibility_requires_arm64_diffusers(isolated_repo: Path) -> None:
    write_lockfile(
        isolated_repo,
        "ml-core-darwin-arm64.txt",
        "3.11",
        body="torch==2.8.0\ntorchvision==0.23.0\ntransformers==5.0.0\nnumpy==2.4.3\ncoremltools==9.0\n",
    )

    errors = contract.validate_platform_lock_runtime_compatibility()

    assert errors == [
        f"{isolated_repo / 'requirements' / 'ml-core-darwin-arm64.txt'} must include a pinned diffusers dependency so the supported Diffusers "
        "security baseline remains part of the checked-in arm64 contract."
    ]


def test_platform_lock_runtime_compatibility_requires_supported_arm64_torch_rotation(isolated_repo: Path) -> None:
    write_lockfile(
        isolated_repo,
        "ml-core-darwin-arm64.txt",
        "3.11",
        body="torch==2.2.2\ntorchvision==0.17.2\ndiffusers==0.38.0\ntransformers==5.0.0\nnumpy==2.4.3\ncoremltools==9.0\n",
    )

    errors = contract.validate_platform_lock_runtime_compatibility()

    assert errors == [
        f"{isolated_repo / 'requirements' / 'ml-core-darwin-arm64.txt'} must rotate to torch==2.8.0 for the supported Apple Silicon security baseline.",
        f"{isolated_repo / 'requirements' / 'ml-core-darwin-arm64.txt'} must rotate to torchvision==0.23.0 for the supported Apple Silicon security baseline.",
    ]


def test_platform_lock_runtime_compatibility_requires_supported_transformers_rotation(isolated_repo: Path) -> None:
    write_lockfile(
        isolated_repo,
        "ml-core-darwin-arm64.txt",
        "3.11",
        body="torch==2.8.0\ntorchvision==0.23.0\ndiffusers==0.38.0\ntransformers==4.57.6\nnumpy==2.4.4\ncoremltools==9.0\n",
    )

    errors = contract.validate_platform_lock_runtime_compatibility()

    assert errors == [
        f"{isolated_repo / 'requirements' / 'ml-core-darwin-arm64.txt'} must rotate to transformers>=5.0.0 "
        "for the supported Transformers security baseline."
    ]


def test_platform_lock_runtime_compatibility_requires_supported_diffusers_rotation(isolated_repo: Path) -> None:
    write_lockfile(
        isolated_repo,
        "ml-core-darwin-arm64.txt",
        "3.11",
        body="torch==2.8.0\ntorchvision==0.23.0\ndiffusers==0.37.1\ntransformers==5.0.0\nnumpy==2.4.4\ncoremltools==9.0\n",
    )

    errors = contract.validate_platform_lock_runtime_compatibility()

    assert errors == [
        f"{isolated_repo / 'requirements' / 'ml-core-darwin-arm64.txt'} must rotate to diffusers>=0.38.0 "
        "for the supported Diffusers security baseline."
    ]


def test_darwin_lock_purity_rejects_triton_on_arm64(isolated_repo: Path) -> None:
    write_lockfile(
        isolated_repo,
        "ml-core-darwin-arm64.txt",
        "3.11",
        body="torch==2.8.0\ntorchvision==0.23.0\ntransformers==5.0.0\nnumpy==2.4.3\ncoremltools==9.0\ntriton==2.2.0\n",
    )

    errors = contract.validate_darwin_lock_purity()

    assert errors == [
        f"{isolated_repo / 'requirements' / 'ml-core-darwin-arm64.txt'} contains forbidden Darwin package 'triton'. "
        "Darwin platform-core lockfiles must not contain Linux/CUDA-only packages."
    ]


def test_darwin_lock_purity_rejects_nvidia_package_on_arm64(isolated_repo: Path) -> None:
    write_lockfile(
        isolated_repo,
        "ml-core-darwin-arm64.txt",
        "3.11",
        body=(
            "torch==2.8.0\n"
            "torchvision==0.23.0\n"
            "transformers==5.0.0\n"
            "numpy==2.4.3\n"
            "coremltools==9.0\n"
            "nvidia-cublas-cu12==12.1.3.1\n"
        ),
    )

    errors = contract.validate_darwin_lock_purity()

    assert errors == [
        f"{isolated_repo / 'requirements' / 'ml-core-darwin-arm64.txt'} contains forbidden Darwin package 'nvidia-cublas-cu12'. "
        "Darwin platform-core lockfiles must not contain Linux/CUDA-only packages."
    ]


def test_darwin_lock_purity_accepts_clean_darwin_locks(isolated_repo: Path) -> None:
    write_lockfile(
        isolated_repo,
        "ml-core-darwin-arm64.txt",
        "3.11",
        body="torch==2.8.0\ntorchvision==0.23.0\ntransformers==5.0.0\nnumpy==2.4.3\ncoremltools==9.0\n",
    )

    errors = contract.validate_darwin_lock_purity()

    assert errors == []
