import importlib.util
from pathlib import Path

import pytest

pytestmark = pytest.mark.unit

PROJECT_ROOT = Path(__file__).resolve().parents[1]
TOOL_PATH = PROJECT_ROOT / "scripts" / "validation" / "check_requirements_lock_contract.py"
SPEC = importlib.util.spec_from_file_location("check_requirements_lock_contract", TOOL_PATH)
assert SPEC is not None and SPEC.loader is not None
contract = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(contract)


def write_makefile(tmp_path: Path, version: str = "3.11") -> None:
    (tmp_path / "requirements").mkdir()
    (tmp_path / "requirements" / "Makefile").write_text(
        f"LOCK_PYTHON_VERSION ?= {version}\n",
        encoding="utf-8",
    )


def write_lockfile(tmp_path: Path, name: str, python_version: str, body: str = "") -> None:
    (tmp_path / "requirements" / name).write_text(
        "\n".join(
            [
                "#",
                f"# This file is autogenerated by pip-compile with Python {python_version}",
                "# by the following command:",
                "#",
                "#    pip-compile ...",
                body,
            ]
        ).rstrip()
        + "\n",
        encoding="utf-8",
    )


@pytest.fixture()
def isolated_repo(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    monkeypatch.setattr(contract, "REPO_ROOT", tmp_path)
    monkeypatch.setattr(contract, "REQUIREMENTS_DIR", tmp_path / "requirements")
    monkeypatch.setattr(contract, "MAKEFILE_PATH", tmp_path / "requirements" / "Makefile")
    write_makefile(tmp_path)
    for name in contract.ALL_LOCK_FILES:
        write_lockfile(tmp_path, name, "3.11")
    return tmp_path


def test_headers_match_expected_python(isolated_repo: Path) -> None:
    expected = contract.read_expected_lock_python_version()
    assert contract.validate_lockfile_headers(expected) == []


def test_header_mismatch_is_reported(isolated_repo: Path) -> None:
    write_lockfile(isolated_repo, "base.txt", "3.12")
    expected = contract.read_expected_lock_python_version()
    errors = contract.validate_lockfile_headers(expected)
    assert errors == [f"{isolated_repo / 'requirements' / 'base.txt'} was generated with Python 3.12; " "expected Python 3.11"]


def test_noncore_optional_lockfile_is_reported(isolated_repo: Path) -> None:
    write_lockfile(isolated_repo, "ml.txt", "3.11")
    errors = contract.validate_noncore_optional_lockfiles_absent()
    assert errors == [
        f"{isolated_repo / 'requirements' / 'ml.txt'} is not part of the checked-in "
        "lockfile contract; remove host-generated non-core ML layer artifacts from the repository"
    ]


def test_platform_lock_wrong_os_marker_is_reported(isolated_repo: Path) -> None:
    write_lockfile(
        isolated_repo,
        "ml-core-linux.txt",
        "3.11",
        body='torch==2.2.2 ; platform_system == "Darwin"\n',
    )
    errors = contract.validate_platform_lock_markers()
    pattern = contract.PLATFORM_LOCK_FORBIDDEN_PATTERNS["ml-core-linux.txt"][0]
    assert errors == [
        f"{isolated_repo / 'requirements' / 'ml-core-linux.txt'}:6 contains forbidden platform marker pattern "
        f"{pattern!r} for this target lockfile"
    ]
