"""Photography runtime closure and non-authorizing bytecode churn contracts."""

from __future__ import annotations

import hashlib
import importlib.machinery
import importlib.util
import marshal
import py_compile
from dataclasses import dataclass
from pathlib import Path
from types import SimpleNamespace

import pytest

from transformation_portal.lux_depth_v4 import runtime

pytestmark = pytest.mark.unit


@dataclass(frozen=True)
class _Parent:
    source_identity_sha256: str
    verification_entries: tuple


def _record_entries(paths):
    entries = {}
    token = runtime.identity._VERIFICATION_ENTRIES.set(entries)
    try:
        for path in paths:
            runtime.identity._record_verification_stat(path)
    finally:
        runtime.identity._VERIFICATION_ENTRIES.reset(token)
    return tuple(entries.values())


@pytest.fixture
def closure(tmp_path, monkeypatch):
    source = tmp_path / "source"
    source.mkdir()
    code = source / "processing.py"
    code.write_text("value = 1\n")
    wheel = tmp_path / "installed"
    wheel.mkdir()
    codec = wheel / "tifffile.py"
    codec.write_text("value = 1\n")
    helper = wheel / "codec_helper.py"
    helper.write_text("value = 1\n")
    state = SimpleNamespace(source=source, code=code, codec=codec, helper=helper, origin=codec, extra_files=[])

    def parent():
        return _Parent("a" * 64, _record_entries([source, code]))

    def spec(name):
        if name == "tifffile":
            return importlib.machinery.ModuleSpec(name, loader=None, origin=str(state.origin))
        return None

    def distribution(_name, **_kwargs):
        records = []
        for path in (codec, helper, *state.extra_files):
            digest, size = runtime.identity._hash_regular_file(path)
            records.append({"path": str(path), "sha256": digest, "size_bytes": size})
        runtime.identity._record_verification_stat(wheel)
        return {"name": "tifffile", "files": records}

    def imports(_names):
        return {
            "tifffile": {
                "origin": str(state.origin),
                "sha256": hashlib.sha256(state.origin.read_bytes()).hexdigest(),
            }
        }

    monkeypatch.setattr(runtime.identity, "prepare_parent_output_runtime_identity", parent)
    monkeypatch.setattr(runtime.identity, "verify_parent_output_runtime_identity", lambda _parent: True)
    monkeypatch.setattr(runtime.identity, "_installed_distribution_index", lambda: {"tifffile": (object(), "1")})
    monkeypatch.setattr(runtime.identity, "_distribution_record", distribution)
    monkeypatch.setattr(runtime.identity, "_import_environment_payload", imports)
    monkeypatch.setattr(runtime.importlib.util, "find_spec", spec)
    return state


def test_shadow_codec_cannot_borrow_installed_distribution_authority(closure, tmp_path):
    closure.origin = tmp_path / "shadow_tifffile.py"
    closure.origin.write_text("value = 1\n")
    with pytest.raises(RuntimeError, match="outside its materialized distribution"):
        runtime.PhotographyRuntime()


def test_actual_codec_bytes_change_identity_and_invalidate_materialized_runtime(closure):
    prepared = runtime.PhotographyRuntime()
    closure.codec.write_text("value = 2\n")
    with pytest.raises(RuntimeError, match="codec import identity changed"):
        prepared.verify()
    assert runtime.PhotographyRuntime().sha256 != prepared.sha256


def test_codec_dependency_mutation_remains_authorizing(closure):
    prepared = runtime.PhotographyRuntime()
    closure.helper.write_text("value = 2\n")
    with pytest.raises(RuntimeError, match="bytes changed"):
        prepared.verify()


def test_new_bytecode_directory_and_rewrites_do_not_invalidate_source_runtime(closure):
    prepared = runtime.PhotographyRuntime()
    cache = closure.source / "__pycache__"
    cache.mkdir()
    bytecode = cache / "processing.cpython-311.pyc"
    bytecode.write_bytes(b"generated bytecode")
    prepared.verify()
    bytecode.write_bytes(b"regenerated bytecode")
    prepared.verify()


def test_existing_bytecode_directory_timestamps_do_not_authorize_code(closure, monkeypatch):
    cache = closure.source / "__pycache__"
    cache.mkdir()
    bytecode = cache / "processing.cpython-311.pyc"
    bytecode.write_bytes(b"compiled")
    monkeypatch.setattr(
        runtime.identity,
        "prepare_parent_output_runtime_identity",
        lambda: _Parent("a" * 64, _record_entries([closure.source, closure.code, cache])),
    )
    prepared = runtime.PhotographyRuntime()
    (cache / "new.cpython-311.pyc").write_bytes(b"new")
    bytecode.write_bytes(b"regenerated")
    prepared.verify()
    (cache / "injected.py").write_text("value = 2\n")
    with pytest.raises(RuntimeError, match="namespace changed"):
        prepared.verify()


@pytest.mark.parametrize("relative", ["added.py", "policy.json", "__pycache__/injected.py"])
def test_authoritative_source_additions_are_rejected(closure, relative):
    prepared = runtime.PhotographyRuntime()
    added = closure.source / relative
    added.parent.mkdir(exist_ok=True)
    added.write_text("{}")
    with pytest.raises(RuntimeError, match="namespace changed"):
        prepared.verify()


def test_source_mutation_and_directory_replacement_are_rejected(closure):
    prepared = runtime.PhotographyRuntime()
    closure.code.write_text("value = 2\n")
    with pytest.raises(RuntimeError, match="bytes changed"):
        prepared.verify()
    prepared = runtime.PhotographyRuntime()
    closure.source.rename(closure.source.with_name("previous"))
    closure.source.mkdir()
    closure.code.write_text("value = 2\n")
    with pytest.raises(RuntimeError, match="namespace changed"):
        prepared.verify()


def test_linked_bytecode_cannot_be_ignored(closure, tmp_path):
    prepared = runtime.PhotographyRuntime()
    other = tmp_path / "outside"
    other.mkdir()
    (closure.source / "__pycache__").symlink_to(other, target_is_directory=True)
    with pytest.raises(RuntimeError, match="namespace changed"):
        prepared.verify()


def test_record_authorized_bytecode_stays_strict(closure):
    cache = closure.codec.parent / "__pycache__"
    cache.mkdir()
    bytecode = cache / "codec.cpython-311.pyc"
    bytecode.write_bytes(b"compiled")
    closure.extra_files.append(bytecode)
    prepared = runtime.PhotographyRuntime()
    bytecode.write_bytes(b"changed")
    with pytest.raises(RuntimeError, match="bytes changed"):
        prepared.verify()


def _source_cache(source, *, replacement=None, optimization=0):
    cache = Path(importlib.util.cache_from_source(str(source), optimization="" if optimization == 0 else str(optimization)))
    py_compile.compile(str(source), cfile=str(cache), doraise=True, optimize=optimization)
    if replacement is not None:
        code = compile(replacement, str(source), "exec", dont_inherit=True, optimize=optimization)
        cache.write_bytes(cache.read_bytes()[:16] + marshal.dumps(code))
    return cache


@pytest.mark.parametrize("optimization", [0, 1, 2])
def test_legitimate_source_bytecode_churn_preserves_runtime_identity(closure, optimization):
    prepared = runtime.PhotographyRuntime()
    cache = _source_cache(closure.code, optimization=optimization)
    prepared.verify()
    cache.write_bytes(cache.read_bytes())
    prepared.verify()


def test_forged_timestamp_valid_bytecode_is_rejected_before_lazy_import(closure, monkeypatch):
    prepared = runtime.PhotographyRuntime()
    _source_cache(closure.code, replacement="value = 999\n")

    def forbidden_loads(*_args, **_kwargs):
        pytest.fail("Runtime verification must never unmarshal untrusted bytecode")

    monkeypatch.setattr(runtime.marshal, "loads", forbidden_loads)
    assert closure.code.read_text() == "value = 1\n"
    with pytest.raises(RuntimeError, match="cached bytecode differs from its source"):
        prepared.verify()


def test_wheel_script_lexical_source_filename_is_verified(closure, tmp_path, monkeypatch):
    site_packages = tmp_path / "environment" / "site-packages"
    site_packages.mkdir(parents=True)
    monkeypatch.syspath_prepend(str(site_packages))
    cache = _source_cache(closure.code)
    filename = str(site_packages / ".." / ".." / "source" / "processing.py")
    assert Path(filename).resolve() == closure.code
    code = compile(closure.code.read_bytes(), filename, "exec", dont_inherit=True, optimize=0)
    cache.write_bytes(cache.read_bytes()[:16] + marshal.dumps(code))
    prepared = runtime.PhotographyRuntime()
    prepared.verify()


def test_rewritten_verified_bytecode_must_revalidate_its_payload(closure):
    cache = _source_cache(closure.code)
    prepared = runtime.PhotographyRuntime()
    prepared.verify()
    original_size = cache.stat().st_size
    _source_cache(closure.code, replacement="value = 2\n")
    assert cache.stat().st_size == original_size
    with pytest.raises(RuntimeError, match="cached bytecode differs from its source"):
        prepared.verify()


def test_oversized_bytecode_is_rejected_before_read_or_compilation(closure, monkeypatch):
    prepared = runtime.PhotographyRuntime()
    cache = _source_cache(closure.code)
    with cache.open("wb") as handle:
        handle.truncate(runtime._MAX_BYTECODE_BYTES + 1)

    def forbidden_compile(*_args, **_kwargs):
        pytest.fail("Oversized bytecode must be rejected before source compilation")

    monkeypatch.setattr(runtime, "compile", forbidden_compile, raising=False)
    with pytest.raises(RuntimeError, match="regular-file bound"):
        prepared.verify()


def test_oversized_bytecode_source_is_rejected_before_compilation(closure, monkeypatch):
    cache = _source_cache(closure.code)
    monkeypatch.setattr(runtime, "_MAX_BYTECODE_SOURCE_BYTES", 1)
    with pytest.raises(RuntimeError, match="regular-file bound"):
        runtime._directory_inventory(cache.parent)
