#!/bin/bash
echo "====================================================================="
echo "TRANSFORMATION PORTAL - REPOSITORY HEALTH CHECK"
echo "====================================================================="
echo ""
echo "📊 REPOSITORY STATS"
echo "---------------------------------------------------------------------"
echo "Python files: $(find . -name "*.py" -not -path "./venv/*" -not -path "./.venv/*" -not -path "./__pycache__/*" | wc -l | tr -d ' ')"
echo "Markdown files: $(find . -name "*.md" | wc -l | tr -d ' ')"
echo "Config files: $(find . -name "*.yaml" -o -name "*.yml" -o -name "*.json" | grep -v node_modules | grep -v venv | wc -l | tr -d ' ')"
echo "Total size: $(du -sh . 2>/dev/null | cut -f1)"
echo ""
echo "🗂️  GIT STATUS"
echo "---------------------------------------------------------------------"
echo "Current branch: $(git branch --show-current)"
echo "Commits behind origin: $(git rev-list HEAD..origin/main --count 2>/dev/null || echo '0')"
echo "Untracked files: $(git status --porcelain | grep '^??' | wc -l | tr -d ' ')"
echo "Modified files: $(git status --porcelain | grep '^ M' | wc -l | tr -d ' ')"
echo "Staged files: $(git status --porcelain | grep '^[AM]' | wc -l | tr -d ' ')"
echo ""
echo "📦 PYTHON ENVIRONMENT"
echo "---------------------------------------------------------------------"
echo "Python version: $(venv/bin/python --version 2>&1)"
echo "Pip version: $(venv/bin/pip --version | cut -d' ' -f2)"
echo "Installed packages: $(venv/bin/pip list 2>/dev/null | tail -n +3 | wc -l | tr -d ' ')"
echo ""
echo "🧹 CLEANUP NEEDED"
echo "---------------------------------------------------------------------"
echo "__pycache__ dirs: $(find . -type d -name "__pycache__" | wc -l | tr -d ' ')"
echo "*.pyc files: $(find . -name "*.pyc" | wc -l | tr -d ' ')"
echo "Log files (root): $(ls -1 *.log 2>/dev/null | wc -l | tr -d ' ')"
echo "JSON files (root): $(ls -1 *.json 2>/dev/null | wc -l | tr -d ' ')"
echo ""
echo "📚 DOCUMENTATION"
echo "---------------------------------------------------------------------"
echo "Root markdown files: $(ls -1 *.md 2>/dev/null | wc -l | tr -d ' ')"
echo "Docs directory exists: $([ -d docs ] && echo 'Yes' || echo 'No')"
echo "README exists: $([ -f README.md ] && echo 'Yes' || echo 'No')"
echo "START_HERE exists: $([ -f START_HERE.md ] && echo 'Yes' || echo 'No')"
echo ""
echo "🧪 TESTING"
echo "---------------------------------------------------------------------"
echo "Test files: $(find tests -name "test_*.py" 2>/dev/null | wc -l | tr -d ' ')"
echo "Pytest installed: $(venv/bin/pip show pytest >/dev/null 2>&1 && echo 'Yes' || echo 'No')"
echo ""
echo "✅ HEALTH SUMMARY"
echo "---------------------------------------------------------------------"
