# Interior Rendering Preset
# Optimized for interior architectural visualizations

depth_model:
  variant: "small"
  backend: "pytorch_mps"
  cache_size: 100

processing:
  depth_aware_denoise:
    enabled: true
    sigma_spatial: 2.5
    preserve_strength: 0.9  # Strong edge preservation for furniture/walls

  zone_tone_mapping:
    enabled: true
    num_zones: 4  # More zones for complex interior lighting
    method: "agx"
    zone_params:
      - {contrast: 1.3, saturation: 1.15, exposure: 0.1}  # Close foreground
      - {contrast: 1.1, saturation: 1.05, exposure: 0.0}  # Foreground
      - {contrast: 1.0, saturation: 1.0, exposure: 0.0}   # Midground
      - {contrast: 0.95, saturation: 0.95, exposure: -0.05}  # Background/windows

  atmospheric_effects:
    enabled: false  # Disabled for interiors

  depth_guided_filters:
    enabled: true
    clarity_strength: 0.6  # Stronger clarity for architectural details

  depth_of_field:
    enabled: false  # Usually not needed for interiors

optimization:
  production_resolution: 1024
  batch_size: 4
