# .github/workflows/python-app.yml
name: build

on:
  push:
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12" ]
    steps:
      - uses: actions/checkout@v5

      # Fast lint gate: no heavy deps
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: flake8 (errors only)
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      # Free space BEFORE installing anything heavy (saves ~20–30 GB)
      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet || true
          sudo rm -rf /usr/local/lib/android || true
          sudo rm -rf /opt/ghc || true
          sudo rm -rf /opt/hostedtoolcache/CodeQL || true
          df -h

      # Install minimal deps for unit tests (CPU only)
      - name: Install lean deps
        env:
          PIP_NO_CACHE_DIR: "1"
        run: |
          pip install -r requirements-ci.txt
          pip install -e .

      - name: Run tests
        run: pytest -v
