name: pylint

on:
  pull_request:
    paths: ["**/*.py"]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12" ]

    steps:
      - uses: actions/checkout@v5

      # Setup Python for matrix
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      # Upgrade pip
      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # Install minimal dependencies for linting
      - name: Install pylint
        run: pip install --no-cache-dir pylint

      # Run pylint on all Python files in the repo
      - name: Run pylint
        run: |
          files=$(git diff --name-only origin/main...HEAD | grep '\.py$' || echo "")
          if [ -z "$files" ]; then
            # If no changed files, lint the entire repo
            echo "No changed Python files detected, linting full repo..."
            pylint $(git ls-files '*.py')
          else
            echo "Linting changed Python files:"
            echo "$files"
            pylint $files
