name: pylint
on:
  pull_request:
    paths: [ "**/*.py" ]

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - run: python -m pip install --upgrade pip

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements-ci.txt') }}

      - run: pip install --no-cache-dir -r requirements-ci.txt
      - run: pip install --no-cache-dir pylint

      - run: |
          git ls-files '*.py' | xargs python -m pylint
