# .github/workflows/build.yml
name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12" ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Free disk space
        run: |
          sudo rm -rf /opt/ghc /usr/local/lib/android || true
          sudo rm -rf /opt/hostedtoolcache/CodeQL || true
          df -h

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install lean deps (CPU-only)
        env:
          PIP_NO_CACHE_DIR: "1"
        run: |
          pip install --no-cache-dir -r requirements-ci.txt --find-links https://download.pytorch.org/whl/cpu

      - name: Lint (critical errors only)
        run: |
          pip install --no-cache-dir flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run tests
        run: pytest -v tests/

  generate-manifest:
    name: Build Montecito Manifest
    needs: [lint-and-test]
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install lean deps
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements-ci.txt

      - name: Run Montecito Manifest Tool
        id: manifest
        shell: bash
        run: |
          set -euo pipefail
          OUT="montecito_manifest.json"

          # Attempt --out flag first
          if python tools/montecito_manifest.py --help 2>/dev/null | grep -qi -- '--out'; then
            python tools/montecito_manifest.py --out "$OUT"
          else
            python tools/montecito_manifest.py
          fi

          # Detect JSON if produced under another name
          if [ ! -f "$OUT" ]; then
            CANDIDATE="$(ls -1t tools/*.json *.json 2>/dev/null | head -n1 || true)"
            [ -n "$CANDIDATE" ] && OUT="$CANDIDATE" || OUT=""
          fi

          echo "manifest_path=$OUT" >> "$GITHUB_OUTPUT"

      - name: Upload manifest artifact
        if: ${{ steps.manifest.outputs.manifest_path != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: montecito-manifest
          path: ${{ steps.manifest.outputs.manifest_path }}
          if-no-files-found: error
