name: issue-summary

on:
  issues:
    types: [opened]

jobs:
  summarize-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Print issue info
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_AUTHOR: ${{ github.event.issue.user.login }}
          BODY: ${{ github.event.issue.body }}
        run: |
          echo "Issue #$ISSUE_NUMBER"
          echo "Title: $ISSUE_TITLE"
          echo "Author: $ISSUE_AUTHOR"
          echo "Body: $BODY"

      - name: Generate summary with OpenAI
        id: generate-summary
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          BODY: ${{ github.event.issue.body }}
        run: |
          echo "Generating AI summary..."
          # Escape for JSON using jq to prevent injection
          USER_CONTENT=$(jq -nc --arg title "$ISSUE_TITLE" --arg body "$BODY" ' "Title: \($title)\n\nBody: \($body)" ')
          JSON_PAYLOAD=$(jq -nc \
            --arg model "gpt-4o-mini" \
            --arg system "You are an assistant that summarizes GitHub issues concisely." \
            --arg user_content "$USER_CONTENT" \
            '{
              model: $model,
              messages: [
                {role: "system", content: $system},
                {role: "user", content: $user_content}
              ]
            }')
          SUMMARY=$(curl -s https://api.openai.com/v1/chat/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -d "$JSON_PAYLOAD" | jq -r '.choices[0].message.content')

          if [ -z "$SUMMARY" ]; then
            SUMMARY="⚠️ Failed to generate summary."
          fi
          echo "summary=$SUMMARY" >> "$GITHUB_OUTPUT"

      - name: Post summary comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            **AI-generated summary:**
            ${{ steps.generate-summary.outputs.summary }}
